---
- name: Deploy traefik
  block:
    - name: Add traefik chart repo
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"

    - name: Deploy traefik chart with values
      kubernetes.core.helm:
        update_repo_cache: true
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: traefik
        create_namespace: true
        values: "{{ lookup('file', role_path + '/files/values.yml') | from_yaml }}"

    - name: Apply certificate
      kubernetes.core.k8s:
        src: "{{ role_path + '/files/traefik-dash-cert.yml' }}"
        state: present
        apply: true

    - name: Apply ingressroute
      kubernetes.core.k8s:
        src: "{{ role_path + '/files/traefik-dash-ingressroute.yml' }}"
        state: present
        apply: true
