---
- name: Deploy traefik
  block:
    - name: Create traefik-dash-cert.yml from template
      ansible.builtin.template:
        src: templates/traefik-dash-cert.yml.j2
        dest: "{{ role_path + '/files/traefik-dash-cert.yml' }}"
        mode: '0755'

    - name: Create traefik-values.yml from template
      ansible.builtin.template:
        src: templates/traefik-values.yml.j2
        dest: "{{ role_path + '/files/traefik-values.yml' }}"
        mode: '0755'

    - name: Create traefik-middleware.yml from template
      ansible.builtin.template:
        src: templates/traefik-middleware.yml.j2
        dest: "{{ role_path + '/files/traefik-middleware.yml' }}"
        mode: '0755'

    - name: Add traefik chart repo
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"

    - name: Deploy traefik chart with values
      kubernetes.core.helm:
        update_repo_cache: true
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: traefik
        create_namespace: true
        values_files: "{{ role_path + '/files/traefik-values.yml' }}"

    - name: Apply certificate
      kubernetes.core.k8s:
        src: "{{ role_path + '/files/traefik-dash-cert.yml' }}"
        state: present
        apply: true

    - name: Apply middleware
      kubernetes.core.k8s:
        src: "{{ role_path + '/files/traefik-middleware.yml' }}"
        state: present
        apply: true
