---
- name: Install k3s k3s_master_2
  ansible.builtin.shell:
    cmd: >
      k3sup join
      --ip {{ hostvars[groups['k3s_masters'][1]].ansible_host }}
      --k3s-channel latest
      --no-extras
      --server
      --server-ip {{ hostvars[groups['k3s_masters'][0]].ansible_host }}
      --tls-san {{ vip }}
      --tls-san {{ cloudflare_fqdn }}
      --user {{ user }}

- name: Install k3s k3s_master_3
  ansible.builtin.shell:
    cmd: >
      k3sup join
      --ip {{ hostvars[groups['k3s_masters'][2]].ansible_host }}
      --k3s-channel latest
      --no-extras
      --server
      --server-ip {{ hostvars[groups['k3s_masters'][0]].ansible_host }}
      --tls-san {{ vip }}
      --tls-san {{ cloudflare_fqdn }}
      --user {{ user }}
